# generated by appcreator
import django_tables2 as tables

from .models import HapaBeleg, HapaPlaceName


class HapaBelegTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    tags = tables.ManyToManyColumn()
    text = tables.TemplateColumn("{{ record.text|safe }}")
    comment = tables.TemplateColumn("{{ record.comment|safe }}")
    internal_comment = tables.TemplateColumn("{{ record.internal_comment|safe }}")
    zot_key = tables.TemplateColumn("{{ record.zotero_id.zot_key }}", orderable=False)

    class Meta:
        model = HapaBeleg
        sequence = (
            "id",
            "...",
            "zotero_id",
            "page_nr",
            "zot_key",
        )
        attrs = {"class": "table table-responsive table-hover"}


class HapaPlaceNameTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    tags = tables.ManyToManyColumn()
    # merge = MergeColumn(verbose_name='keep | remove', accessor='pk')
    beleg = tables.columns.ManyToManyColumn(verbose_name="Belege")
    wortbildung = tables.TemplateColumn("{{ record.wortbildung|safe }}")
    etymology = tables.TemplateColumn("{{ record.etymology|safe }}")
    syntax = tables.TemplateColumn("{{ record.syntax|safe }}")
    comment = tables.TemplateColumn("{{ record.comment|safe }}")
    internal_comment = tables.TemplateColumn("{{ record.internal_comment|safe }}")

    class Meta:
        model = HapaPlaceName
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}
        order_by = [
            "-id",
        ]
