# generated by appcreator
import django_tables2 as tables

from . models import (
    HapaBeleg,
    HapaPlaceName
)


class HapaBelegTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    tags = tables.ManyToManyColumn()
    # merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = HapaBeleg
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class HapaPlaceNameTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    tags = tables.ManyToManyColumn()
    # merge = MergeColumn(verbose_name='keep | remove', accessor='pk')
    beleg = tables.columns.ManyToManyColumn()

    class Meta:
        model = HapaPlaceName
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}
