# Generated by Django 3.1.6 on 2021-02-02 17:09

from django_ckeditor_5.fields import CKEditor5Field
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hapabeleg",
            name="text",
            field=CKEditor5Field(
                blank=True,
                help_text="ausgewähltes Quellenzitaten",
                null=True,
                verbose_name="Textauszug",
            ),
        ),
        migrations.AlterField(
            model_name="hapaplacename",
            name="description",
            field=CKEditor5Field(
                blank=True,
                help_text="Besprechung der Etymologie und Wortbildung des Ortsnamens",
                null=True,
                verbose_name="Etymologie und Wortbildung",
            ),
        ),
        migrations.AlterField(
            model_name="hapaplacename",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Wird aus den Angaben von Beiten- und Längengrad befüllt)",
                null=True,
                srid=4326,
                verbose_name="Koordinaten",
            ),
        ),
    ]
