# Generated by Django 3.1.6 on 2021-02-09 10:07

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0004_hapaplacename_wortbildung"),
    ]

    operations = [
        migrations.AddField(
            model_name="hapaplacename",
            name="etymology",
            field=CKEditor5Field(
                blank=True,
                help_text="Besprechung der Etymologie des Ortsnamens",
                null=True,
                verbose_name="Etymologie",
            ),
        ),
    ]
