# Generated by Django 3.1.6 on 2021-02-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0006_hapaplacename_syntax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hapaplacename",
            name="description",
        ),
    ]
