# Generated by Django 3.1.6 on 2021-02-09 10:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0007_remove_hapaplacename_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hapaplacename',
            name='fuzzy_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Ungefähre Lokalisierung historischer Orte', null=True, srid=4326, verbose_name='Ungefähre Ortsangabe'),
        ),
    ]
