# Generated by Django 3.1.6 on 2021-03-01 09:18

from django_ckeditor_5.fields import CKEditor5Field
import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("archiv", "0009_hapaplacename_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="hapabeleg",
            name="comment",
            field=CKEditor5Field(
                blank=True, help_text="Kommentar", null=True, verbose_name="Kommentar"
            ),
        ),
        migrations.AddField(
            model_name="hapabeleg",
            name="internal_comment",
            field=CKEditor5Field(
                blank=True,
                help_text="Kommentar (intern)",
                null=True,
                verbose_name="Kommentar (intern)",
            ),
        ),
        migrations.AddField(
            model_name="hapabeleg",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="hapaplacename",
            name="comment",
            field=CKEditor5Field(
                blank=True, help_text="Kommentar", null=True, verbose_name="Kommentar"
            ),
        ),
        migrations.AddField(
            model_name="hapaplacename",
            name="internal_comment",
            field=CKEditor5Field(
                blank=True,
                help_text="Kommentar (intern)",
                null=True,
                verbose_name="Kommentar (intern)",
            ),
        ),
    ]
