# Generated by Django 3.1.6 on 2021-03-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0010_auto_20210301_0918"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hapabeleg",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="hapaplacename",
            name="legacy_id",
        ),
    ]
