# Generated by Django 3.1.6 on 2021-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0012_auto_20210408_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="hapaplacename",
            name="alternative_names",
            field=models.TextField(
                blank=True,
                help_text="Alternative Namen, verwende '; ' als Trennzeichen",
                verbose_name="Alternative Namen",
            ),
        ),
    ]
