# Generated by Django 3.1.6 on 2021-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0014_auto_20211209_1422"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hapabeleg",
            options={"ordering": ["short_quote", "page_nr"], "verbose_name": "Beleg"},
        ),
        migrations.AddField(
            model_name="hapaplacename",
            name="historic_names",
            field=models.TextField(
                blank=True,
                help_text="Historische(r) Name(n), verwende '; ' als Trennzeichen",
                verbose_name="Historische(r) Name(n)",
            ),
        ),
    ]
