# Generated by Django 3.1.5 on 2021-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gn_places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonamesplace',
            name='gn_cc2',
        ),
        migrations.AddField(
            model_name='geonamesplace',
            name='gn_cc2',
            field=models.CharField(blank=True, help_text='Alternate Country Codes', max_length=250, null=True, verbose_name='Alternate Country Codes'),
        ),
        migrations.AlterField(
            model_name='geonamesplace',
            name='gn_country_code',
            field=models.CharField(blank=True, help_text='Country Code', max_length=250, null=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='geonamesplace',
            name='gn_feature_class',
            field=models.CharField(blank=True, help_text='Feature Class', max_length=250, null=True, verbose_name='Feature Class'),
        ),
        migrations.AlterField(
            model_name='geonamesplace',
            name='gn_feature_code',
            field=models.CharField(blank=True, help_text='Feature Code', max_length=250, null=True, verbose_name='Feature Code'),
        ),
    ]
