# Generated by Django 3.1.5 on 2021-01-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('gn_places', '0002_auto_20210111_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonamesplace',
            name='gn_feature',
            field=models.ForeignKey(blank=True, help_text="The Place's Feature Code as SKOS", null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabs.skosconcept', verbose_name='Feature Code as SKOS'),
        ),
    ]
