# generated by appcreator
from django.urls import path
from . import dal_views

app_name = 'gn_places'
urlpatterns = [
    path(
        'geonamesplace-autocomplete/',
        dal_views.GeoNamesPlaceAC.as_view(),
        name='geonamesplace-autocomplete'
    ),
]
