# generated by appcreator
import django_tables2 as tables
from django_tables2.utils import A

from browsing.browsing_utils import MergeColumn
from . models import (
    GeoNamesPlace
)


class GeoNamesPlaceTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')
    gn_cc2 = tables.columns.ManyToManyColumn()

    class Meta:
        model = GeoNamesPlace
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}

