# generated by appcreator
from django.conf.urls import url
from . import views

app_name = 'gn_places'
urlpatterns = [
    url(
        r'^geonamesplace/$',
        views.GeoNamesPlaceListView.as_view(),
        name='geonamesplace_browse'
    ),
    url(
        r'^geonamesplace/detail/(?P<pk>[0-9]+)$',
        views.GeoNamesPlaceDetailView.as_view(),
        name='geonamesplace_detail'
    ),
    url(
        r'^geonamesplace/create/$',
        views.GeoNamesPlaceCreate.as_view(),
        name='geonamesplace_create'
    ),
    url(
        r'^geonamesplace/edit/(?P<pk>[0-9]+)$',
        views.GeoNamesPlaceUpdate.as_view(),
        name='geonamesplace_edit'
    ),
    url(
        r'^geonamesplace/delete/(?P<pk>[0-9]+)$',
        views.GeoNamesPlaceDelete.as_view(),
        name='geonamesplace_delete'),
]
